### ISSUE TITLE
Does this repository can be used in Windows?

### ISSUE THREAD

**Issue by DeLeonOscar** [okaki-keisuke/Carla-with-RL#1]
Hello,

I am  currently doing an project on DRL in Autonomous Vehicle in CARLA. I saw that your project required Linux, it is possible to run this project in Windows?

Thank you,
Oscar De Leon

**Comment by okaki-keisuke** [comment]
Hi!
Thanks for asking.

I have no mean of trying this on Windows so I'm not sure but I think it works.

I made Env following the tutorial at the URL below. If CARLA Python API has same specification as Linux and Windows, it should work fine. Even if it doesn't work, I think it will work with a little modification.

Unrelated, but the DRL code was modified from the code used in AirSim on Windows.

↓ tutorial
https://carla.readthedocs.io/en/latest/tutorials/
↓ I used this as reference when I made Env.
https://github.com/cjy1992/gym-carla

Keisuke Okaki
