### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by tqlblzj** [okaki-keisuke/Carla-with-RL#2]
hi, I want to learn more about this code, could you upload the documented work.

**Comment by okaki-keisuke** [comment]
Hi, Thank you for asking.

I have not published my thesis.
Please take a look at Thesis.pdf I just uploaded to github.
But please note that it is a Japanese paper.

**Comment by tqlblzj** [comment]
> Hi, Thank you for asking.
> 
> I have not published my thesis. Please take a look at Thesis.pdf I just uploaded to github. But please note that it is a Japanese paper.

OK! Thank you!
